CREATE TABLE IF NOT EXISTS collection_run (
    id VARCHAR(36) PRIMARY KEY,
    source VARCHAR(30) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(12) NOT NULL,
    item_count INTEGER,
    message VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS roadside_spot (
    spot_id VARCHAR(64) PRIMARY KEY,
    cell_id VARCHAR(64),
    road_id VARCHAR(64),
    road_name VARCHAR(255),
    spot_type VARCHAR(100),
    area_code VARCHAR(20) NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    parking_status VARCHAR(20),
    cell_status VARCHAR(20),
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_changed_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS roadside_state_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spot_id VARCHAR(64) NOT NULL,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    parking_status VARCHAR(20),
    cell_status VARCHAR(20),
    run_id VARCHAR(36) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_roadside_event_time ON roadside_state_event(spot_id, observed_at);

CREATE TABLE IF NOT EXISTS offstreet_lot (
    lot_id VARCHAR(64) PRIMARY KEY,
    lot_name VARCHAR(255),
    address VARCHAR(500),
    total_car INTEGER,
    tw97_x VARCHAR(40),
    tw97_y VARCHAR(40),
    available_car_raw VARCHAR(30),
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_changed_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS offstreet_state_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id VARCHAR(64) NOT NULL,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    available_car_raw VARCHAR(30),
    run_id VARCHAR(36) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_offstreet_event_time ON offstreet_state_event(lot_id, observed_at);
